export const COUNTRY_MAP = [
  { name: "Afghanistan", code: "AF", dial_code: "+93", flag: "🇦🇫" },
  { name: "Albania", code: "AL", dial_code: "+355", flag: "🇦🇱" },
  { name: "Algeria", code: "DZ", dial_code: "+213", flag: "🇩🇿" },
  { name: "Andorra", code: "AD", dial_code: "+376", flag: "🇦🇩" },
  { name: "Angola", code: "AO", dial_code: "+244", flag: "🇦🇴" },
  { name: "Arabia Saudita", code: "SA", dial_code: "+966", flag: "🇸🇦" },
  { name: "Argentina", code: "AR", dial_code: "+54", flag: "🇦🇷" },
  { name: "Armenia", code: "AM", dial_code: "+374", flag: "🇦🇲" },
  { name: "Australia", code: "AU", dial_code: "+61", flag: "🇦🇺" },
  { name: "Austria", code: "AT", dial_code: "+43", flag: "🇦🇹" },
  { name: "Azerbaigian", code: "AZ", dial_code: "+994", flag: "🇦🇿" },
  { name: "Bahamas", code: "BS", dial_code: "+1", flag: "🇧🇸" },
  { name: "Bahrein", code: "BH", dial_code: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", code: "BD", dial_code: "+880", flag: "🇧🇩" },
  { name: "Belgio", code: "BE", dial_code: "+32", flag: "🇧🇪" },
  { name: "Belize", code: "BZ", dial_code: "+501", flag: "🇧🇿" },
  { name: "Benin", code: "BJ", dial_code: "+229", flag: "🇧🇯" },
  { name: "Bielorussia", code: "BY", dial_code: "+375", flag: "🇧🇾" },
  { name: "Bolivia", code: "BO", dial_code: "+591", flag: "🇧🇴" },
  { name: "Bosnia ed Erzegovina", code: "BA", dial_code: "+387", flag: "🇧🇦" },
  { name: "Botswana", code: "BW", dial_code: "+267", flag: "🇧🇼" },
  { name: "Brasile", code: "BR", dial_code: "+55", flag: "🇧🇷" },
  { name: "Bulgaria", code: "BG", dial_code: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", dial_code: "+226", flag: "🇧🇫" },
  { name: "Cambogia", code: "KH", dial_code: "+855", flag: "🇰🇭" },
  { name: "Camerun", code: "CM", dial_code: "+237", flag: "🇨🇲" },
  { name: "Canada", code: "CA", dial_code: "+1", flag: "🇨🇦" },
  { name: "Capo Verde", code: "CV", dial_code: "+238", flag: "🇨🇻" },
  { name: "Cile", code: "CL", dial_code: "+56", flag: "🇨🇱" },
  { name: "Cina", code: "CN", dial_code: "+86", flag: "🇨🇳" },
  { name: "Cipro", code: "CY", dial_code: "+357", flag: "🇨🇾" },
  { name: "Colombia", code: "CO", dial_code: "+57", flag: "🇨🇴" },
  { name: "Corea del Sud", code: "KR", dial_code: "+82", flag: "🇰🇷" },
  { name: "Costa d'Avorio", code: "CI", dial_code: "+225", flag: "🇨🇮" },
  { name: "Costa Rica", code: "CR", dial_code: "+506", flag: "🇨🇷" },
  { name: "Croazia", code: "HR", dial_code: "+385", flag: "🇭🇷" },
  { name: "Cuba", code: "CU", dial_code: "+53", flag: "🇨🇺" },
  { name: "Danimarca", code: "DK", dial_code: "+45", flag: "🇩🇰" },
  { name: "Ecuador", code: "EC", dial_code: "+593", flag: "🇪🇨" },
  { name: "Egitto", code: "EG", dial_code: "+20", flag: "🇪🇬" },
  { name: "El Salvador", code: "SV", dial_code: "+503", flag: "🇸🇻" },
  { name: "Emirati Arabi Uniti", code: "AE", dial_code: "+971", flag: "🇦🇪" },
  { name: "Estonia", code: "EE", dial_code: "+372", flag: "🇪🇪" },
  { name: "Etiopia", code: "ET", dial_code: "+251", flag: "🇪🇹" },
  { name: "Filippine", code: "PH", dial_code: "+63", flag: "🇵🇭" },
  { name: "Finlandia", code: "FI", dial_code: "+358", flag: "🇫🇮" },
  { name: "Francia", code: "FR", dial_code: "+33", flag: "🇫🇷" },
  { name: "Georgia", code: "GE", dial_code: "+995", flag: "🇬🇪" },
  { name: "Germania", code: "DE", dial_code: "+49", flag: "🇩🇪" },
  { name: "Giamaica", code: "JM", dial_code: "+1", flag: "🇯🇲" },
  { name: "Giappone", code: "JP", dial_code: "+81", flag: "🇯🇵" },
  { name: "Giordania", code: "JO", dial_code: "+962", flag: "🇯🇴" },
  { name: "Grecia", code: "GR", dial_code: "+30", flag: "🇬🇷" },
  { name: "Guatemala", code: "GT", dial_code: "+502", flag: "🇬🇹" },
  { name: "Hong Kong", code: "HK", dial_code: "+852", flag: "🇭🇰" },
  { name: "India", code: "IN", dial_code: "+91", flag: "🇮🇳" },
  { name: "Indonesia", code: "ID", dial_code: "+62", flag: "🇮🇩" },
  { name: "Iran", code: "IR", dial_code: "+98", flag: "🇮🇷" },
  { name: "Iraq", code: "IQ", dial_code: "+964", flag: "🇮🇶" },
  { name: "Irlanda", code: "IE", dial_code: "+353", flag: "🇮🇪" },
  { name: "Islanda", code: "IS", dial_code: "+354", flag: "🇮🇸" },
  { name: "Israele", code: "IL", dial_code: "+972", flag: "🇮🇱" },
  { name: "Italia", code: "IT", dial_code: "+39", flag: "🇮🇹" },
  { name: "Kazakistan", code: "KZ", dial_code: "+7", flag: "🇰🇿" },
  { name: "Kenya", code: "KE", dial_code: "+254", flag: "🇰🇪" },
  { name: "Kuwait", code: "KW", dial_code: "+965", flag: "🇰🇼" },
  { name: "Lettonia", code: "LV", dial_code: "+371", flag: "🇱🇻" },
  { name: "Libano", code: "LB", dial_code: "+961", flag: "🇱🇧" },
  { name: "Libia", code: "LY", dial_code: "+218", flag: "🇱🇾" },
  { name: "Liechtenstein", code: "LI", dial_code: "+423", flag: "🇱🇮" },
  { name: "Lituania", code: "LT", dial_code: "+370", flag: "🇱🇹" },
  { name: "Lussemburgo", code: "LU", dial_code: "+352", flag: "🇱🇺" },
  { name: "Macedonia del Nord", code: "MK", dial_code: "+389", flag: "🇲🇰" },
  { name: "Malesia", code: "MY", dial_code: "+60", flag: "🇲🇾" },
  { name: "Malta", code: "MT", dial_code: "+356", flag: "🇲🇹" },
  { name: "Marocco", code: "MA", dial_code: "+212", flag: "🇲🇦" },
  { name: "Messico", code: "MX", dial_code: "+52", flag: "🇲🇽" },
  { name: "Moldavia", code: "MD", dial_code: "+373", flag: "🇲🇩" },
  { name: "Monaco", code: "MC", dial_code: "+377", flag: "🇲🇨" },
  { name: "Mongolia", code: "MN", dial_code: "+976", flag: "🇲🇳" },
  { name: "Montenegro", code: "ME", dial_code: "+382", flag: "🇲🇪" },
  { name: "Nepal", code: "NP", dial_code: "+977", flag: "🇳🇵" },
  { name: "Nigeria", code: "NG", dial_code: "+234", flag: "🇳🇬" },
  { name: "Norvegia", code: "NO", dial_code: "+47", flag: "🇳🇴" },
  { name: "Nuova Zelanda", code: "NZ", dial_code: "+64", flag: "🇳🇿" },
  { name: "Paesi Bassi", code: "NL", dial_code: "+31", flag: "🇳🇱" },
  { name: "Pakistan", code: "PK", dial_code: "+92", flag: "🇵🇰" },
  { name: "Palestina", code: "PS", dial_code: "+970", flag: "🇵🇸" },
  { name: "Panama", code: "PA", dial_code: "+507", flag: "🇵🇦" },
  { name: "Paraguay", code: "PY", dial_code: "+595", flag: "🇵🇾" },
  { name: "Perù", code: "PE", dial_code: "+51", flag: "🇵🇪" },
  { name: "Polonia", code: "PL", dial_code: "+48", flag: "🇵🇱" },
  { name: "Portogallo", code: "PT", dial_code: "+351", flag: "🇵🇹" },
  { name: "Qatar", code: "QA", dial_code: "+974", flag: "🇶🇦" },
  { name: "Regno Unito", code: "GB", dial_code: "+44", flag: "🇬🇧" },
  { name: "Repubblica Ceca", code: "CZ", dial_code: "+420", flag: "🇨🇿" },
  { name: "Repubblica Dominicana", code: "DO", dial_code: "+1", flag: "🇩🇴" },
  { name: "Romania", code: "RO", dial_code: "+40", flag: "🇷🇴" },
  { name: "Russia", code: "RU", dial_code: "+7", flag: "🇷🇺" },
  { name: "San Marino", code: "SM", dial_code: "+378", flag: "🇸🇲" },
  { name: "Senegal", code: "SN", dial_code: "+221", flag: "🇸🇳" },
  { name: "Serbia", code: "RS", dial_code: "+381", flag: "🇷🇸" },
  { name: "Singapore", code: "SG", dial_code: "+65", flag: "🇸🇬" },
  { name: "Slovacchia", code: "SK", dial_code: "+421", flag: "🇸🇰" },
  { name: "Slovenia", code: "SI", dial_code: "+386", flag: "🇸🇮" },
  { name: "Somalia", code: "SO", dial_code: "+252", flag: "🇸🇴" },
  { name: "Spagna", code: "ES", dial_code: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", code: "LK", dial_code: "+94", flag: "🇱🇰" },
  { name: "Stati Uniti", code: "US", dial_code: "+1", flag: "🇺🇸" },
  { name: "Sudafrica", code: "ZA", dial_code: "+27", flag: "🇿🇦" },
  { name: "Svezia", code: "SE", dial_code: "+46", flag: "🇸🇪" },
  { name: "Svizzera", code: "CH", dial_code: "+41", flag: "🇨🇭" },
  { name: "Taiwan", code: "TW", dial_code: "+886", flag: "🇹🇼" },
  { name: "Thailandia", code: "TH", dial_code: "+66", flag: "🇹🇭" },
  { name: "Tunisia", code: "TN", dial_code: "+216", flag: "🇹🇳" },
  { name: "Turchia", code: "TR", dial_code: "+90", flag: "🇹🇷" },
  { name: "Ucraina", code: "UA", dial_code: "+380", flag: "🇺🇦" },
  { name: "Ungheria", code: "HU", dial_code: "+36", flag: "🇭🇺" },
  { name: "Uruguay", code: "UY", dial_code: "+598", flag: "🇺🇾" },
  { name: "Venezuela", code: "VE", dial_code: "+58", flag: "🇻🇪" },
  { name: "Vietnam", code: "VN", dial_code: "+84", flag: "🇻🇳" }
].sort((a, b) => a.name.localeCompare(b.name));

export const MONTHS = [
  "Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", 
  "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"
];

export const ITALIAN_PROVINCES = [
  "Agrigento", "Alessandria", "Ancona", "Aosta", "Arezzo", "Ascoli Piceno", "Asti", "Avellino", 
  "Bari", "Barletta-Andria-Trani", "Belluno", "Benevento", "Bergamo", "Biella", "Bologna", "Bolzano", "Brescia", "Brindisi", 
  "Cagliari", "Caltanissetta", "Campobasso", "Carbonia-Iglesias", "Caserta", "Catania", "Catanzaro", "Chieti", "Como", "Cosenza", "Cremona", "Crotone", "Cuneo", 
  "Enna", "Fermo", "Ferrara", "Firenze", "Foggia", "Forlì-Cesena", "Frosinone", 
  "Genova", "Gorizia", "Grosseto", 
  "Imperia", "Isernia", 
  "La Spezia", "L'Aquila", "Latina", "Lecce", "Lecco", "Livorno", "Lodi", "Lucca", 
  "Macerata", "Mantova", "Massa-Carrara", "Matera", "Medio Campidano", "Messina", "Milano", "Modena", "Monza e della Brianza", 
  "Napoli", "Novara", "Nuoro", 
  "Ogliastra", "Olbia-Tempio", "Oristano", 
  "Padova", "Palermo", "Parma", "Pavia", "Perugia", "Pesaro e Urbino", "Pescara", "Piacenza", "Pisa", "Pistoia", "Pordenone", "Potenza", "Prato", 
  "Ragusa", "Ravenna", "Reggio Calabria", "Reggio Emilia", "Rieti", "Rimini", "Roma", "Rovigo", 
  "Salerno", "Sassari", "Savona", "Siena", "Siracusa", "Sondrio", 
  "Taranto", "Teramo", "Terni", "Torino", "Trapani", "Trento", "Treviso", "Trieste", 
  "Udine", 
  "Varese", "Venezia", "Verbano-Cusio-Ossola", "Vercelli", "Verona", "Vibo Valentia", "Vicenza", "Viterbo"
];

export const DAYS = Array.from({ length: 31 }, (_, i) => i + 1);

export const REGEX_VALIDATORS = {
  NAME: "^[a-zA-Z\\s']+$",
  FISCAL_CODE: "^[a-zA-Z0-9]{16}$",
  EMAIL: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
  PASSWORD: "^(?=.*[A-Z])(?=.*[!@#$&*])(?=.*[0-9]).{8,}$",
  PHONE: "^[0-9\\s]+$"
};