// Mappa Completa Nazione -> Codice ISO
export const COUNTRY_MAP = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antartide", code: "AQ" },
  { name: "Antigua e Barbuda", code: "AG" },
  { name: "Arabia Saudita", code: "SA" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaigian", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrein", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belgio", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bielorussia", code: "BY" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia ed Erzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Brasile", code: "BR" },
  { name: "Brunei", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambogia", code: "KH" },
  { name: "Camerun", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Capo Verde", code: "CV" },
  { name: "Ciad", code: "TD" },
  { name: "Cile", code: "CL" },
  { name: "Cina", code: "CN" },
  { name: "Cipro", code: "CY" },
  { name: "Città del Vaticano", code: "VA" },
  { name: "Colombia", code: "CO" },
  { name: "Comore", code: "KM" },
  { name: "Corea del Nord", code: "KP" },
  { name: "Corea del Sud", code: "KR" },
  { name: "Costa d'Avorio", code: "CI" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croazia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Danimarca", code: "DK" },
  { name: "Dominica", code: "DM" },
  { name: "Ecuador", code: "EC" },
  { name: "Egitto", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Emirati Arabi Uniti", code: "AE" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Etiopia", code: "ET" },
  { name: "Fiji", code: "FJ" },
  { name: "Filippine", code: "PH" },
  { name: "Finlandia", code: "FI" },
  { name: "Francia", code: "FR" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Georgia del Sud e Sandwich Australi", code: "GS" },
  { name: "Germania", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Giamaica", code: "JM" },
  { name: "Giappone", code: "JP" },
  { name: "Gibilterra", code: "GI" },
  { name: "Gibuti", code: "DJ" },
  { name: "Giordania", code: "JO" },
  { name: "Grecia", code: "GR" },
  { name: "Grenada", code: "GD" },
  { name: "Groenlandia", code: "GL" },
  { name: "Guadalupa", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guiana Francese", code: "GF" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea Equatoriale", code: "GQ" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Irlanda", code: "IE" },
  { name: "Islanda", code: "IS" },
  { name: "Isola Bouvet", code: "BV" },
  { name: "Isola Christmas", code: "CX" },
  { name: "Isola di Man", code: "IM" },
  { name: "Isola Norfolk", code: "NF" },
  { name: "Isole Cayman", code: "KY" },
  { name: "Isole Cocos (Keeling)", code: "CC" },
  { name: "Isole Cook", code: "CK" },
  { name: "Isole Falkland", code: "FK" },
  { name: "Isole Fær Øer", code: "FO" },
  { name: "Isole Heard e McDonald", code: "HM" },
  { name: "Isole Marianne Settentrionali", code: "MP" },
  { name: "Isole Marshall", code: "MH" },
  { name: "Isole Minori Esterne degli USA", code: "UM" },
  { name: "Isole Pitcairn", code: "PN" },
  { name: "Isole Salomone", code: "SB" },
  { name: "Isole Turks e Caicos", code: "TC" },
  { name: "Isole Vergini Americane", code: "VI" },
  { name: "Isole Vergini Britanniche", code: "VG" },
  { name: "Israele", code: "IL" },
  { name: "Italia", code: "IT" },
  { name: "Kazakistan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kirghizistan", code: "KG" },
  { name: "Kiribati", code: "KI" },
  { name: "Kuwait", code: "KW" },
  { name: "Laos", code: "LA" },
  { name: "Lesotho", code: "LS" },
  { name: "Lettonia", code: "LV" },
  { name: "Libano", code: "LB" },
  { name: "Liberia", code: "LR" },
  { name: "Libia", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lituania", code: "LT" },
  { name: "Lussemburgo", "code": "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia del Nord", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malesia", code: "MY" },
  { name: "Maldive", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marocco", code: "MA" },
  { name: "Martinica", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Messico", code: "MX" },
  { name: "Micronesia", code: "FM" },
  { name: "Moldavia", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Montserrat", code: "MS" },
  { name: "Mozambico", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norvegia", code: "NO" },
  { name: "Nuova Caledonia", code: "NC" },
  { name: "Nuova Zelanda", code: "NZ" },
  { name: "Oman", code: "OM" },
  { name: "Paesi Bassi", code: "NL" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestina", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua Nuova Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Perù", code: "PE" },
  { name: "Polinesia Francese", code: "PF" },
  { name: "Polonia", code: "PL" },
  { name: "Porto Rico", code: "PR" },
  { name: "Portogallo", code: "PT" },
  { name: "Qatar", code: "QA" },
  { name: "Regno Unito", code: "GB" },
  { name: "Repubblica Ceca", code: "CZ" },
  { name: "Repubblica Centrafricana", code: "CF" },
  { name: "Repubblica del Congo", code: "CG" },
  { name: "Repubblica Democratica del Congo", code: "CD" },
  { name: "Repubblica Dominicana", code: "DO" },
  { name: "Riunione", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Ruanda", code: "RW" },
  { name: "Russia", code: "RU" },
  { name: "Sahara Occidentale", code: "EH" },
  { name: "Saint Kitts e Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Vincent e Grenadine", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "Samoa Americane", code: "AS" },
  { name: "San Marino", code: "SM" },
  { name: "Sant'Elena", code: "SH" },
  { name: "São Tomé e Príncipe", code: "ST" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Siria", code: "SY" },
  { name: "Slovacchia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Somalia", code: "SO" },
  { name: "Spagna", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Stati Uniti", code: "US" },
  { name: "Sudafrica", code: "ZA" },
  { name: "Sudan", code: "SD" },
  { name: "Sudan del Sud", code: "SS" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard e Jan Mayen", code: "SJ" },
  { name: "Svezia", code: "SE" },
  { name: "Svizzera", code: "CH" },
  { name: "Swaziland", code: "SZ" },
  { name: "Tagikistan", code: "TJ" },
  { name: "Taiwan", code: "TW" },
  { name: "Tanzania", code: "TZ" },
  { name: "Terre Australi e Antartiche Francesi", code: "TF" },
  { name: "Territorio Britannico dell'Oceano Indiano", code: "IO" },
  { name: "Thailandia", code: "TH" },
  { name: "Timor Est", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad e Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turchia", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV" },
  { name: "Ucraina", code: "UA" },
  { name: "Uganda", code: "UG" },
  { name: "Ungheria", code: "HU" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Wallis e Futuna", code: "WF" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" }
];

export const MONTHS = [
  "Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", 
  "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"
];

export const ITALIAN_PROVINCES = [
  "Agrigento", "Alessandria", "Ancona", "Aosta", "Arezzo", "Ascoli Piceno", "Asti", "Avellino", 
  "Bari", "Barletta-Andria-Trani", "Belluno", "Benevento", "Bergamo", "Biella", "Bologna", "Bolzano", "Brescia", "Brindisi", 
  "Cagliari", "Caltanissetta", "Campobasso", "Carbonia-Iglesias", "Caserta", "Catania", "Catanzaro", "Chieti", "Como", "Cosenza", "Cremona", "Crotone", "Cuneo", 
  "Enna", "Fermo", "Ferrara", "Firenze", "Foggia", "Forlì-Cesena", "Frosinone", 
  "Genova", "Gorizia", "Grosseto", 
  "Imperia", "Isernia", 
  "La Spezia", "L'Aquila", "Latina", "Lecce", "Lecco", "Livorno", "Lodi", "Lucca", 
  "Macerata", "Mantova", "Massa-Carrara", "Matera", "Medio Campidano", "Messina", "Milano", "Modena", "Monza e della Brianza", 
  "Napoli", "Novara", "Nuoro", 
  "Ogliastra", "Olbia-Tempio", "Oristano", 
  "Padova", "Palermo", "Parma", "Pavia", "Perugia", "Pesaro e Urbino", "Pescara", "Piacenza", "Pisa", "Pistoia", "Pordenone", "Potenza", "Prato", 
  "Ragusa", "Ravenna", "Reggio Calabria", "Reggio Emilia", "Rieti", "Rimini", "Roma", "Rovigo", 
  "Salerno", "Sassari", "Savona", "Siena", "Siracusa", "Sondrio", 
  "Taranto", "Teramo", "Terni", "Torino", "Trapani", "Trento", "Treviso", "Trieste", 
  "Udine", 
  "Varese", "Venezia", "Verbano-Cusio-Ossola", "Vercelli", "Verona", "Vibo Valentia", "Vicenza", "Viterbo"
];

export const DAYS = Array.from({ length: 31 }, (_, i) => i + 1);
export const YEARS = Array.from({ length: 110 }, (_, i) => new Date().getFullYear() - i);